[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
board_build.filesystem_size = 1m
board_build.usbstack = tinyusb

lib_deps =
    LittleFS
    WebServer
    https://github.com/sfranzyshen/ESP-Arduino-Lua.git
    Links2004/WebSockets
    Adafruit Protomatter
    Adafruit GFX Library